---
title: "HW3 Group5"
author: "Tianyi Zhou, Mduduzi Langwenya, Shengchen Fu, Yanxi Gao, Lin Wang"
date: "2/22/2019"
output: word_document
---
```{r message=FALSE, warning=FALSE}
#load packages
library(tidyverse)
library(knitr)
library(readxl)
library(readr)
library(writexl) 
#load revenue data
revenue<-read_csv("VTREVCODE16.csv")
#load ED emergency department data
ED<- read_csv("VTED16.csv")
#load inpatient data
inpatient<-read_csv("VTINP16_upd.csv")
```


###Question 1
####Select main variables from inpatient data to tell the stories
The storyies of specific patients
UNIQ: 507033, 40436, 859382, 1585831, 200760, 3692, 690326

```{r}
#select hospital number, admission type, admission source, age, sex, discharge status, primary payer, charges, diagonosis, procedure and patient days columns in inpatient
inpatient_q1<-inpatient%>% select (UNIQ,hnum2,ATYPE,asour,intage,sex,dstat,PPAY,CHRGS,DX1,DX2,DX3,DX4,DX5,PX1,PX2,PX3,pdays) 
#select same columns in ED
ED_q1<-ED %>% select (UNIQ,hnum2,ATYPE,asour,intage,sex,dstat,PPAY,CHRGS,DX1,DX2,DX3,DX4,DX5,PX1,PX2,PX3,pdays) 
## We are doing this part in R because the file is big and it is faster to search for the patient in csv
## When patient went to ER first, their data can be found in both inpatient and ED data. 
#select unique number,revenue code, revenue charges, number of revenue units, primary cost center and CPT code columns in revenue
revenue_q1<-revenue %>% select(UNIQ,REVCODE,REVCHRGS,REVUNITS,PCCR,CPT)
```

#####Patient 1
```{r}
#patient 507033
inpatient_q1 %>%  filter(UNIQ ==507033)
revenue_q1 %>% filter(UNIQ ==507033) %>% group_by(REVCODE) %>% arrange(desc(REVCHRGS))
```

#####Patient 2

```{r}
#patient 40436
inpatient_q1 %>%  filter(UNIQ ==40436) 
revenue_q1 %>% filter(UNIQ ==40436) %>% group_by(REVCODE) %>% arrange(desc(REVCHRGS))
```

#####Patient 3

```{r}
#patient 859382
inpatient_q1 %>%  filter(UNIQ ==859382)

ED_q1 %>% filter(UNIQ ==859382)

revenue_q1 %>% filter(UNIQ ==859382) %>% group_by(REVCODE) %>% arrange(desc(REVCHRGS))

```

#####Patient 4

```{r}
#patient 1585831
inpatient_q1 %>% filter(UNIQ ==1585831) 

ED_q1 %>%filter(UNIQ ==1585831) 

revenue_q1 %>% filter(UNIQ ==1585831) %>% group_by(REVCODE) %>% arrange(desc(REVCHRGS))
```

#####Patient 5

```{r}
#patient 200760
inpatient_q1 %>% filter(UNIQ ==200760) 

ED_q1 %>% filter(UNIQ ==200760) 

revenue_q1 %>% filter(UNIQ ==200760) %>% group_by(REVCODE) %>% arrange(desc(REVCHRGS))
```

#####Patient 6

```{r}
#patient 3692
inpatient_q1 %>%filter(UNIQ ==3692) 

ED_q1 %>% filter(UNIQ ==3692) 

revenue_q1 %>% filter(UNIQ ==3692) %>% group_by(REVCODE) %>% arrange(desc(REVCHRGS))
```

#####Patient 7

```{r}
#patient 690326
inpatient_q1 %>%  filter(UNIQ ==690326)

revenue_q1 %>% filter(UNIQ ==690326) %>% group_by(REVCODE) %>% arrange(desc(REVCHRGS))

```

###Question 2
```{r}
#select 3 major insurance payers
num=c(1,2,6,7)
inpatient_major = inpatient %>% filter(PPAY%in%num)
inpatient_major = inpatient_major %>% mutate(Payers = ifelse(PPAY==1,"MEDICARE",
                                     ifelse(PPAY==2,"MEDICAID","Commercial Payers")))
#create table
charge = inpatient_major %>% 
  group_by(Payers, MDC) %>% 
  summarise(Charges=round(sum(CHRGS)/1000000)) %>% 
  drop_na() #drop the rows where at least one column contains NA
xtabs(Charges ~ Payers + MDC, data = charge)

#age and sex for major payers
sex = inpatient_major %>% 
  group_by(Payers, sex) %>% 
  summarise(number=n()) %>% 
  drop_na()
age = inpatient_major %>% 
  group_by(Payers, intage) %>% 
  summarise(number=n()) %>% 
  drop_na()
age_sex = inpatient_major %>% 
  group_by(Payers, intage, sex) %>% 
  summarise(number=n()) %>% 
  drop_na()

#export data for piechart and tables
write_xlsx(x = charge, path = "charge.xlsx", col_names = TRUE)
write_xlsx(x = sex, path = "sex.xlsx", col_names = TRUE)
write_xlsx(x = age, path = "age.xlsx", col_names = TRUE)
write_xlsx(x = age_sex, path = "age_sex.xlsx", col_names = TRUE)
```

###Question 3
```{r}

```

